/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OpticaRouteImport } from './routes/optica'
import { Route as GlosarRouteImport } from './routes/glosar'
import { Route as ExploratorRouteImport } from './routes/explorator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OpticaRoute = OpticaRouteImport.update({
  id: '/optica',
  path: '/optica',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosarRoute = GlosarRouteImport.update({
  id: '/glosar',
  path: '/glosar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploratorRoute = ExploratorRouteImport.update({
  id: '/explorator',
  path: '/explorator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorator': typeof ExploratorRoute
  '/glosar': typeof GlosarRoute
  '/optica': typeof OpticaRoute
  '/quiz': typeof QuizRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorator': typeof ExploratorRoute
  '/glosar': typeof GlosarRoute
  '/optica': typeof OpticaRoute
  '/quiz': typeof QuizRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorator': typeof ExploratorRoute
  '/glosar': typeof GlosarRoute
  '/optica': typeof OpticaRoute
  '/quiz': typeof QuizRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorator'
    | '/glosar'
    | '/optica'
    | '/quiz'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explorator' | '/glosar' | '/optica' | '/quiz' | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/explorator'
    | '/glosar'
    | '/optica'
    | '/quiz'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploratorRoute: typeof ExploratorRoute
  GlosarRoute: typeof GlosarRoute
  OpticaRoute: typeof OpticaRoute
  QuizRoute: typeof QuizRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optica': {
      id: '/optica'
      path: '/optica'
      fullPath: '/optica'
      preLoaderRoute: typeof OpticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosar': {
      id: '/glosar'
      path: '/glosar'
      fullPath: '/glosar'
      preLoaderRoute: typeof GlosarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorator': {
      id: '/explorator'
      path: '/explorator'
      fullPath: '/explorator'
      preLoaderRoute: typeof ExploratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploratorRoute: ExploratorRoute,
  GlosarRoute: GlosarRoute,
  OpticaRoute: OpticaRoute,
  QuizRoute: QuizRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
