
delete from public.ai_knowledge_entries
where tissue = 'muschi'
  and structure_slug in (
    'muschi-cap-gat',
    'muschi-brat-umar',
    'muschi-mana-antebrat',
    'muschi-trunchi',
    'muschi-membru-inferior',
    'muschi-picior'
  );

insert into public.ai_knowledge_entries
  (tissue, structure_slug, model_selection_id, body_region, category, title_ro, content_ro, priority)
values
  ('muschi', 'muschi-cap-gat', 'muschi-cap-gat', 'cap_gat', 'anatomie',
   'Context muscular: Mușchii capului și gâtului',
   'Mușchii capului și gâtului controlează expresiile faciale, masticația, poziția capului și mișcările cervicale. Ei lucrează împreună cu coloana cervicală, mandibula și structurile laringelui.',
   8),
  ('muschi', 'muschi-cap-gat', 'muschi-cap-gat', 'cap_gat', 'simptome',
   'Simptome musculare posibile în cap și gât',
   'durere sau tensiune la nivelul cefei, rigiditate, spasme, durere la întoarcerea capului, sensibilitate la palpare, oboseală musculară după poziție prelungită sau durere care se accentuează la mișcare.',
   7),
  ('muschi', 'muschi-cap-gat', 'muschi-cap-gat', 'cap_gat', 'cauze_posibile',
   'Cauze posibile pentru durerea musculară în cap și gât',
   'postură prelungită, suprasolicitare, mișcare bruscă, contractură musculară, tensiune după efort sau somn într-o poziție incomodă. După traumă cervicală trebuie luate în calcul și leziuni non-musculare.',
   7),
  ('muschi', 'muschi-cap-gat', 'muschi-cap-gat', 'cap_gat', 'recomandari',
   'Măsuri educaționale pentru mușchii capului și gâtului',
   'redu efortul și mișcările dureroase, urmărește evoluția, evită manipulările bruște ale gâtului și cere evaluare medicală dacă durerea este severă, apare după traumatism sau se asociază cu simptome neurologice.',
   6),
  ('muschi', 'muschi-cap-gat', 'muschi-cap-gat', 'cap_gat', 'semne_alarma',
   'Semne de alarmă pentru cap și gât',
   'consult medical rapid pentru traumă cervicală, slăbiciune, amorțeală, amețeală severă, febră, rigiditate importantă, durere progresivă intensă, dificultate la înghițire sau respirație.',
   9),
  ('muschi', 'muschi-cap-gat', 'muschi-cap-gat', 'cap_gat', 'intrebari_clarificare',
   'Întrebări utile pentru mușchii capului și gâtului',
   'Durerea a apărut după poziție prelungită sau după lovitură? Poți mișca gâtul? Există amorțeală, slăbiciune, febră sau amețeală? Durerea coboară spre braț?',
   5),

  ('muschi', 'muschi-brat-umar', 'muschi-brat-umar', 'membru_superior', 'anatomie',
   'Context muscular: Mușchii brațului și umărului',
   'Mușchii umărului și brațului stabilizează articulația umărului și permit ridicarea, coborârea, rotația, flexia și extensia brațului. Ei includ grupe precum deltoidul, coafa rotatorie, bicepsul și tricepsul.',
   8),
  ('muschi', 'muschi-brat-umar', 'muschi-brat-umar', 'membru_superior', 'simptome',
   'Simptome musculare posibile în braț și umăr',
   'durere la ridicarea brațului, slăbiciune la împins sau tras, sensibilitate musculară, spasm, oboseală, limitarea mișcării, durere după efort sau durere apărută brusc în timpul unei contracții.',
   7),
  ('muschi', 'muschi-brat-umar', 'muschi-brat-umar', 'membru_superior', 'cauze_posibile',
   'Cauze posibile pentru durerea musculară în braț și umăr',
   'suprasolicitare, întindere musculară, contractură, contuzie, efort repetitiv sau mișcare bruscă. Pentru durere profundă după cădere pot exista și probleme articulare, tendinoase sau osoase.',
   7),
  ('muschi', 'muschi-brat-umar', 'muschi-brat-umar', 'membru_superior', 'recomandari',
   'Măsuri educaționale pentru mușchii brațului și umărului',
   'evită ridicările dureroase și efortul intens, urmărește dacă forța revine, aplică măsuri simple de protecție și cere evaluare dacă durerea persistă, limitează mișcarea sau apare după traumatism.',
   6),
  ('muschi', 'muschi-brat-umar', 'muschi-brat-umar', 'membru_superior', 'semne_alarma',
   'Semne de alarmă pentru braț și umăr',
   'consult medical pentru deformare, imposibilitatea ridicării brațului, durere severă după cădere, slăbiciune accentuată, amorțeală, umflare mare, vânătaie extinsă sau senzație de ruptură.',
   9),
  ('muschi', 'muschi-brat-umar', 'muschi-brat-umar', 'membru_superior', 'intrebari_clarificare',
   'Întrebări utile pentru mușchii brațului și umărului',
   'Durerea apare când ridici brațul? A început după efort sau după lovitură? Ai pierdut forță? Există vânătaie, umflare, amorțeală sau deformare?',
   5),

  ('muschi', 'muschi-mana-antebrat', 'muschi-mana-antebrat', 'mana_antebrat', 'anatomie',
   'Context muscular: Mușchii mâinii și antebrațului',
   'Mușchii mâinii și antebrațului controlează prinderea, flexia și extensia încheieturii, mișcările degetelor și rotația antebrațului. Sunt solicitați în scris, tastat, sport, prindere și activități repetitive.',
   8),
  ('muschi', 'muschi-mana-antebrat', 'muschi-mana-antebrat', 'mana_antebrat', 'simptome',
   'Simptome musculare posibile în mână și antebraț',
   'durere la strângerea pumnului, oboseală la prindere, tensiune în antebraț, crampe, sensibilitate la palpare, durere la flexia sau extensia încheieturii, scăderea forței de prindere.',
   7),
  ('muschi', 'muschi-mana-antebrat', 'muschi-mana-antebrat', 'mana_antebrat', 'cauze_posibile',
   'Cauze posibile pentru durerea musculară în mână și antebraț',
   'suprasolicitare prin mișcări repetitive, efort de prindere, întindere musculară, crampă, contractură sau contuzie. Durerea cu amorțeală poate implica și nervi sau tendoane, nu doar mușchi.',
   7),
  ('muschi', 'muschi-mana-antebrat', 'muschi-mana-antebrat', 'mana_antebrat', 'recomandari',
   'Măsuri educaționale pentru mușchii mâinii și antebrațului',
   'redu activitățile repetitive, evită prinderea dureroasă, urmărește forța și sensibilitatea. Cere evaluare dacă apare amorțeală, slăbiciune, durere severă, umflare importantă sau simptome după traumă.',
   6),
  ('muschi', 'muschi-mana-antebrat', 'muschi-mana-antebrat', 'mana_antebrat', 'semne_alarma',
   'Semne de alarmă pentru mână și antebraț',
   'consult medical pentru imposibilitatea folosirii mâinii, amorțeală, slăbiciune, degete reci sau palide, durere severă după traumă, umflare rapidă sau pierderea controlului mișcărilor fine.',
   9),
  ('muschi', 'muschi-mana-antebrat', 'muschi-mana-antebrat', 'mana_antebrat', 'intrebari_clarificare',
   'Întrebări utile pentru mușchii mâinii și antebrațului',
   'Durerea apare la prindere sau la mișcarea încheieturii? Ai amorțeală în degete? A fost efort repetitiv sau lovitură? Forța de prindere este mai mică?',
   5),

  ('muschi', 'muschi-trunchi', 'muschi-trunchi', 'trunchi', 'anatomie',
   'Context muscular: Mușchii trunchiului',
   'Mușchii trunchiului stabilizează coloana, susțin postura, ajută respirația și permit flexia, extensia și rotația corpului. Include regiuni abdominale, toracice și ale spatelui.',
   8),
  ('muschi', 'muschi-trunchi', 'muschi-trunchi', 'trunchi', 'simptome',
   'Simptome musculare posibile în trunchi',
   'durere la răsucire, durere la aplecare, tensiune locală, spasm, sensibilitate la palpare, durere după efort sau durere accentuată de respirație profundă în cazul mușchilor toracici.',
   7),
  ('muschi', 'muschi-trunchi', 'muschi-trunchi', 'trunchi', 'cauze_posibile',
   'Cauze posibile pentru durerea musculară în trunchi',
   'suprasolicitare, ridicare greșită, tuse intensă, contractură, întindere abdominală sau a spatelui, contuzie. Durerea toracică sau abdominală severă poate avea cauze non-musculare.',
   7),
  ('muschi', 'muschi-trunchi', 'muschi-trunchi', 'trunchi', 'recomandari',
   'Măsuri educaționale pentru mușchii trunchiului',
   'evită mișcările care agravează durerea, monitorizează respirația și intensitatea. Cere evaluare pentru durere toracică, dificultate de respirație, traumă, febră sau durere abdominală puternică.',
   6),
  ('muschi', 'muschi-trunchi', 'muschi-trunchi', 'trunchi', 'semne_alarma',
   'Semne de alarmă pentru trunchi',
   'consult urgent pentru durere toracică, dificultate de respirație, tuse cu sânge, durere abdominală severă, traumă majoră, febră, slăbiciune progresivă sau pierderea controlului vezicii/intestinului.',
   9),
  ('muschi', 'muschi-trunchi', 'muschi-trunchi', 'trunchi', 'intrebari_clarificare',
   'Întrebări utile pentru mușchii trunchiului',
   'Durerea apare la aplecare, răsucire sau respirație? A fost ridicare grea sau lovitură? Ai dificultate de respirație, febră sau durere care nu seamănă cu o durere musculară?',
   5),

  ('muschi', 'muschi-membru-inferior', 'muschi-membru-inferior', 'membru_inferior', 'anatomie',
   'Context muscular: Mușchii coapsei și gambei',
   'Mușchii coapsei și gambei controlează mersul, alergarea, săriturile, stabilitatea genunchiului și mișcările gleznei. Include cvadricepsul, ischiogambierii, adductorii și musculatura gambei.',
   8),
  ('muschi', 'muschi-membru-inferior', 'muschi-membru-inferior', 'membru_inferior', 'simptome',
   'Simptome musculare posibile în coapsă și gambă',
   'durere la mers sau alergare, crampe, tensiune musculară, slăbiciune, durere la urcat scări, sensibilitate locală, spasm, vânătaie după efort sau durere bruscă în timpul mișcării.',
   7),
  ('muschi', 'muschi-membru-inferior', 'muschi-membru-inferior', 'membru_inferior', 'cauze_posibile',
   'Cauze posibile pentru durerea musculară în coapsă și gambă',
   'crampă, întindere musculară, contractură, suprasolicitare la alergare, contuzie sau ruptură musculară posibilă. Durerea cu umflare importantă ori roșeață poate necesita evaluare medicală.',
   7),
  ('muschi', 'muschi-membru-inferior', 'muschi-membru-inferior', 'membru_inferior', 'recomandari',
   'Măsuri educaționale pentru mușchii coapsei și gambei',
   'redu alergarea sau efortul dureros, urmărește mersul și forța, evită revenirea bruscă la efort. Consultă medicul pentru durere severă, imposibilitate de sprijin, umflare mare sau vânătaie extinsă.',
   6),
  ('muschi', 'muschi-membru-inferior', 'muschi-membru-inferior', 'membru_inferior', 'semne_alarma',
   'Semne de alarmă pentru coapsă și gambă',
   'consult medical pentru imposibilitate de sprijin, durere severă apărută brusc, pocnet, vânătaie mare, umflare importantă, amorțeală, slăbiciune sau gambă roșie și caldă.',
   9),
  ('muschi', 'muschi-membru-inferior', 'muschi-membru-inferior', 'membru_inferior', 'intrebari_clarificare',
   'Întrebări utile pentru mușchii coapsei și gambei',
   'Durerea a apărut în alergare sau după efort? Poți merge normal? Există crampe, vânătaie, umflare sau pocnet? Durerea este în coapsă, gambă sau lângă genunchi?',
   5),

  ('muschi', 'muschi-picior', 'muschi-picior', 'picior', 'anatomie',
   'Context muscular: Mușchii piciorului',
   'Mușchii piciorului ajută la echilibru, susțin arcul plantar, mișcă degetele și adaptează talpa la sol în mers. Sunt solicitați în alergare, stat mult în picioare și încălțăminte nepotrivită.',
   8),
  ('muschi', 'muschi-picior', 'muschi-picior', 'picior', 'simptome',
   'Simptome musculare posibile în picior',
   'crampe în talpă, durere la mers, oboseală plantarǎ, tensiune, sensibilitate locală, durere la mișcarea degetelor sau durere după stat prelungit în picioare.',
   7),
  ('muschi', 'muschi-picior', 'muschi-picior', 'picior', 'cauze_posibile',
   'Cauze posibile pentru durerea musculară în picior',
   'suprasolicitare, crampe, încălțăminte nepotrivită, efort prelungit, contractură sau contuzie. Durerea ascuțită după traumatism poate implica și oase, ligamente sau tendoane.',
   7),
  ('muschi', 'muschi-picior', 'muschi-picior', 'picior', 'recomandari',
   'Măsuri educaționale pentru mușchii piciorului',
   'redu mersul dureros, urmărește dacă poți sprijini normal și evită încălțămintea care agravează simptomele. Cere evaluare pentru durere severă, traumă, deformare sau imposibilitate de sprijin.',
   6),
  ('muschi', 'muschi-picior', 'muschi-picior', 'picior', 'semne_alarma',
   'Semne de alarmă pentru picior',
   'consult medical pentru imposibilitate de sprijin, deformare, umflare mare, amorțeală, degete reci sau palide, rană, durere severă după traumă sau agravare rapidă.',
   9),
  ('muschi', 'muschi-picior', 'muschi-picior', 'picior', 'intrebari_clarificare',
   'Întrebări utile pentru mușchii piciorului',
   'Durerea apare când calci sau când miști degetele? A fost alergare, stat mult în picioare sau lovitură? Poți sprijini pe picior? Există amorțeală sau umflare?',
   5);
