
insert into public.anatomy_structures
  (slug, model_selection_id, tissue, body_region,
   name_ro, common_name_ro, scientific_name_ro, display_name_ro,
   english_name, missing_ro_display_name)
values
  ('cvadriceps','cvadriceps','muschi','coapsa',
   'Cvadriceps','Cvadricepsul','Cvadriceps','Cvadricepsul','Quadriceps',false),
  ('ischiogambieri','ischiogambieri','muschi','coapsa',
   'Ischiogambieri','Ischiogambierii','Ischiogambieri','Ischiogambierii','Hamstrings',false),
  ('adductori','adductori','muschi','coapsa',
   'Adductori','Adductorii coapsei','Adductori','Adductorii coapsei','Adductors',false),
  ('coafa-rotatorilor','coafa-rotatorilor','muschi','umar_centura_scapulara',
   'Coafa rotatorilor','Coafa rotatorilor','Coafa rotatorilor','Coafa rotatorilor','Rotator cuff',false),
  ('muschii-fesieri','muschii-fesieri','muschi','sold',
   'Mușchii fesieri','Mușchii fesieri','Mușchii fesieri','Mușchii fesieri','Gluteal muscles',false),
  ('muschii-gambei','muschii-gambei','muschi','gamba',
   'Mușchii gambei (molet)','Mușchii gambei','Mușchii gambei','Mușchii gambei','Calf muscles',false),
  ('muschii-tibiali-peronieri','muschii-tibiali-peronieri','muschi','gamba',
   'Mușchii tibiali și peronieri','Mușchii tibiali și peronieri',
   'Mușchii tibiali și peronieri','Mușchii tibiali și peronieri',
   'Tibial and fibular muscles',false),
  ('muschii-spatelui-superficiali','muschii-spatelui-superficiali','muschi','spate',
   'Mușchii superficiali ai spatelui','Mușchii superficiali ai spatelui',
   'Mușchii superficiali ai spatelui','Mușchii superficiali ai spatelui',
   'Superficial back muscles',false),
  ('muschii-spatelui-profunzi','muschii-spatelui-profunzi','muschi','spate',
   'Mușchii profunzi ai spatelui','Mușchii profunzi ai spatelui',
   'Mușchii profunzi ai spatelui','Mușchii profunzi ai spatelui',
   'Deep back muscles',false),
  ('muschii-abdominali','muschii-abdominali','muschi','abdomen',
   'Mușchii abdominali','Mușchii abdominali','Mușchii abdominali','Mușchii abdominali',
   'Abdominal muscles',false),
  ('muschii-pieptului','muschii-pieptului','muschi','torace',
   'Mușchii pieptului','Mușchii pieptului','Mușchii pieptului','Mușchii pieptului',
   'Chest muscles',false),
  ('muschii-gatului','muschii-gatului','muschi','cap_gat',
   'Mușchii gâtului','Mușchii gâtului','Mușchii gâtului','Mușchii gâtului',
   'Neck muscles',false),
  ('muschii-masticatori','muschii-masticatori','muschi','cap_gat',
   'Mușchii masticatori','Mușchii masticatori','Mușchii masticatori','Mușchii masticatori',
   'Masticatory muscles',false),
  ('muschii-soldului-profunzi','muschii-soldului-profunzi','muschi','sold',
   'Mușchii profunzi ai șoldului','Mușchii profunzi ai șoldului',
   'Mușchii profunzi ai șoldului','Mușchii profunzi ai șoldului',
   'Deep hip muscles',false),
  ('muschii-bratului-anteriori','muschii-bratului-anteriori','muschi','brat',
   'Mușchii anteriori ai brațului','Mușchii anteriori ai brațului',
   'Mușchii anteriori ai brațului','Mușchii anteriori ai brațului',
   'Anterior arm muscles',false),
  ('muschii-bratului-posteriori','muschii-bratului-posteriori','muschi','brat',
   'Mușchii posteriori ai brațului','Mușchii posteriori ai brațului',
   'Mușchii posteriori ai brațului','Mușchii posteriori ai brațului',
   'Posterior arm muscles',false),
  ('schelet-cap','os:craniu','os','cap_craniu',
   'Oasele capului','Oasele capului','Craniu','Oasele capului','Skull bones',false),
  ('schelet-coloana','os:coloana','os','coloana',
   'Coloana vertebrală','Coloana vertebrală','Coloana vertebrală','Coloana vertebrală',
   'Vertebral column',false),
  ('schelet-torace','os:torace','os','torace',
   'Scheletul toracelui','Scheletul toracelui','Cutia toracică','Scheletul toracelui',
   'Thoracic skeleton',false),
  ('schelet-membrul-superior','os:antebrat','os','antebrat',
   'Oasele membrului superior','Oasele membrului superior',
   'Membrul superior','Oasele membrului superior','Upper limb bones',false),
  ('schelet-membrul-inferior','os:gamba','os','gamba',
   'Oasele membrului inferior','Oasele membrului inferior',
   'Membrul inferior','Oasele membrului inferior','Lower limb bones',false)
on conflict (slug) do update set
  display_name_ro = excluded.display_name_ro,
  english_name    = excluded.english_name,
  updated_at      = now();

delete from public.ai_knowledge_entries
where tissue = 'muschi'
  and structure_slug in (
    'muschi-cap-gat','muschi-brat-umar','muschi-mana-antebrat',
    'muschi-trunchi','muschi-membru-inferior','muschi-picior'
  );


insert into public.ai_knowledge_entries
  (tissue, structure_slug, model_selection_id, body_region,
   category, title_ro, content_ro, priority)
values

('muschi','muschii-capului-gatului','muschi:muschii-capului-gatului','cap_gat',
 'anatomie','Mușchii capului și gâtului — anatomie',
 'Mușchii capului controlează expresiile feței (mimică, zâmbet, încruntare) și masticația. Mușchii gâtului permit rotația, flexia și extensia capului și stabilizează coloana cervicală. Principalii mușchi: sternocleidomastoidian (rotație cap), trapez superior (ridicare umăr/cap), scaleni (flexie gât), mușchii mimicii (orbicular, zigomatic, frontal), maseter și temporal (mestecat).',
 8),
('muschi','muschii-capului-gatului','muschi:muschii-capului-gatului','cap_gat',
 'simptome','Simptome frecvente la mușchii capului și gâtului',
 'durere sau tensiune în ceafă și gât, rigiditate la întoarcerea capului, senzație de cap greu, durere de cap de tip tensional, spasm muscular palpabil, durere care pornește din gât spre umăr, oboseală musculară după stat prelungit la birou sau la calculator.',
 7),
('muschi','muschii-capului-gatului','muschi:muschii-capului-gatului','cap_gat',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii capului și gâtului',
 'postură proastă la birou sau telefon, tensiune acumulată (stres), somn în poziție incomodă, curent de aer rece direct pe gât, mișcare bruscă de rotație, contractură după efort sau sport de contact, scrâșnit din dinți (bruxism) pentru mușchii masticatori.',
 7),
('muschi','muschii-capului-gatului','muschi:muschii-capului-gatului','cap_gat',
 'recomandari','Ce poți face pentru mușchii capului și gâtului',
 'odihnă și reducerea activităților care agravează durerea; aplicare de căldură locală (10-15 minute) pentru contracturi; stretching ușor al gâtului; corectarea posturii la birou; evitarea pernei prea înalte sau prea joase. Consultă un medic dacă durerea nu cedează în câteva zile sau se intensifică.',
 6),
('muschi','muschii-capului-gatului','muschi:muschii-capului-gatului','cap_gat',
 'semne_alarma','Semne de alarmă pentru capul și gâtul — mergi urgent la doctor',
 'durere foarte intensă apărută brusc ("cea mai puternică durere din viața mea"), rigiditate severă a gâtului cu febră (posibilă meningită), amorțeală sau slăbiciune în brațe sau mâini, amețeală intensă cu vedere dublă, durere după traumatism (accident, cădere), dificultate la înghițire sau respirație, durere cu scădere în greutate inexplicabilă.',
 9),
('muschi','muschii-capului-gatului','muschi:muschii-capului-gatului','cap_gat',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la capul și gâtul',
 'Durerea a apărut brusc sau s-a instalat treptat? Ai dormit în poziție incomodă sau ai stat mult la calculator? Poți întoarce capul în ambele direcții? Există amorțeală, furnicături sau slăbiciune în braț? Ai febră, amețeală sau vedere tulbure? Durerea a apărut după un traumatism?',
 5),

('muschi','muschii-umarului','muschi:muschii-umarului','umar_centura_scapulara',
 'anatomie','Mușchii umărului — anatomie',
 'Articulația umărului are cea mai mare mobilitate din corp, permisă de un set complex de mușchi. Deltoidul (anterior, lateral, posterior) ridică și rotește brațul. Coafa rotatorilor (supraspinos, infraspinos, subscapular, rotund mic) stabilizează capul humeral în cavitate. Bicepsul și pectoral mare contribuie la mișcările brațului față de umăr.',
 8),
('muschi','muschii-umarului','muschi:muschii-umarului','umar_centura_scapulara',
 'simptome','Simptome frecvente la mușchii umărului',
 'durere la ridicarea brațului peste nivelul umărului, slăbiciune la împins sau tras, durere nocturnă (mai ales pe partea afectată), dificultate la îmbrăcat sau pieptănat, senzație de blocare sau clicuri la mișcare, sensibilitate la palpare pe umăr, durere care coboară spre cot.',
 7),
('muschi','muschii-umarului','muschi:muschii-umarului','umar_centura_scapulara',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii umărului',
 'suprasolicitare prin mișcări repetitive deasupra capului (sport, muncă), contractură musculară, impingement subacromian (compresie tendon), ruptură de coafă rotatorie după efort sau traumă, bursită, luxație de umăr sau fractură (după cădere). Durerea poate fi și referată de coloana cervicală.',
 7),
('muschi','muschii-umarului','muschi:muschii-umarului','umar_centura_scapulara',
 'recomandari','Ce poți face pentru mușchii umărului',
 'evită ridicările deasupra capului și mișcările dureroase; odihnă relativă (nu imobilizare totală); gheață în primele 48h după traumatism acut, apoi căldură; stretching ușor al umărului; consultă un medic pentru evaluare și fizioterapie dacă durerea persistă mai mult de o săptămână.',
 6),
('muschi','muschii-umarului','muschi:muschii-umarului','umar_centura_scapulara',
 'semne_alarma','Semne de alarmă pentru umăr — mergi la doctor',
 'deformare vizibilă a umărului (posibilă luxație sau fractură), imposibilitatea completă de mișcare a brațului, durere severă după cădere pe braț întins, amorțeală sau furnicături pe întregul braț sau mână, umflare rapidă sau vânătaie extinsă, durere care nu s-a ameliorat deloc în 2 săptămâni.',
 9),
('muschi','muschii-umarului','muschi:muschii-umarului','umar_centura_scapulara',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la umăr',
 'Durerea apare la ridicarea brațului sau tot timpul? A început după efort sau după o cădere/lovitură? Ai slăbiciune la împins sau tras? Există amorțeală sau furnicături în braț ori mână? Durerea te trezește noaptea? Ai mai avut probleme la același umăr?',
 5),

('muschi','muschii-bratului','muschi:muschii-bratului','brat',
 'anatomie','Mușchii brațului — anatomie',
 'Brațul are două grupe principale: față (biceps brahial și brahial) care flectează cotul și supin antebrațul, și spate (triceps brahial și anconeu) care extind cotul. Bicepsul este de obicei cel mai "vizibil" mușchi al brațului. Coracobrahialul stabilizează brațul față de torace.',
 8),
('muschi','muschii-bratului','muschi:muschii-bratului','brat',
 'simptome','Simptome frecvente la mușchii brațului',
 'durere la îndoirea sau întinderea cotului, slăbiciune la ridicarea greutăților, sensibilitate la palparea bicepsului sau tricepsului, crampe după efort, durere surdă după antrenament intens, umflare localizată după traumă.',
 7),
('muschi','muschii-bratului','muschi:muschii-bratului','brat',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii brațului',
 'febra musculară după efort intens (DOMS), suprasolicitare la sal sau sport, întindere musculară (ruptură parțială), contuzie directă, crampe, ruptură completă de biceps (pocnet, deformare) după efort maximal. Durerea poate veni și de la umăr sau cot.',
 7),
('muschi','muschii-bratului','muschi:muschii-bratului','brat',
 'recomandari','Ce poți face pentru mușchii brațului',
 'reducerea efortului care provoacă durerea; odihnă activă (mișcări ușoare, fără greutăți); gheață după traumatism acut; revenire graduală la activitate. Consultă un medic dacă există deformare a brațului, pierdere semnificativă de forță sau durere foarte intensă după o mișcare bruscă.',
 6),
('muschi','muschii-bratului','muschi:muschii-bratului','brat',
 'semne_alarma','Semne de alarmă pentru brațul — mergi la doctor',
 'pocnet urmat de durere intensă și pierderea forței (posibilă ruptură completă), deformare vizibilă a brațului, vânătaie extinsă apărută rapid, amorțeală sau slăbiciune progresivă, imposibilitatea extinderii cotului după traumatism.',
 9),
('muschi','muschii-bratului','muschi:muschii-bratului','brat',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la brațul',
 'Durerea apare la îndoirea sau întinderea cotului? A apărut după efort (sport, greutăți) sau după lovitură? Ai auzit sau simțit un pocnet? Brațul arată normal sau există deformare? Există slăbiciune sau amorțeală?',
 5),

('muschi','muschii-antebratului','muschi:muschii-antebratului','antebrat',
 'anatomie','Mușchii antebrațului — anatomie',
 'Antebrațul conține două grupe: față (flexori: flexor carpian radial și ulnar, palmaris lung, flexor digitorum) care îndoaie încheietura și degetele, și spate (extensori: extensor carpian, extensor digitorum) care le extind. Pronator și supinator rotesc antebrațul. Brahioradialul flexează cotul și este cel mai vizibil lateral.',
 8),
('muschi','muschii-antebratului','muschi:muschii-antebratului','antebrat',
 'simptome','Simptome frecvente la mușchii antebrațului',
 'durere sau arsură în antebraț la tastare, scris sau prindere, oboseală rapidă a mâinii, crampe la strângerea pumnului, tensiune sau umflare ușoară pe fața interioară sau exterioară a antebrațului, slăbiciune la prindere, durere care se extinde spre cot (epicondilită laterală = "cotul tenismanului") sau spre interior (epicondilită medială = "cotul golfistului").',
 7),
('muschi','muschii-antebratului','muschi:muschii-antebratului','antebrat',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii antebrațului',
 'mișcări repetitive (tastare, prindere, scris), suprasolicitare la sport cu rachetă sau greutăți, contractură, crampă, contuzie. Epicondilita (cotul tenismanului sau golfistului) este o cauză frecventă. Amorțeala și furnicăturile pot indica compresie de nerv median (sindrom de tunel carpian).',
 7),
('muschi','muschii-antebratului','muschi:muschii-antebratului','antebrat',
 'recomandari','Ce poți face pentru mușchii antebrațului',
 'pauze regulate de la activitățile repetitive; stretching al antebrațului (îndoaie încheietura cu cealaltă mână); gheață pe zona dureroasă 10 minute; ergonomie la birou (poziție corectă a mâinilor). Consultă un medic dacă apar amorțeală, slăbiciune sau dacă durerea persistă peste 2 săptămâni.',
 6),
('muschi','muschii-antebratului','muschi:muschii-antebratului','antebrat',
 'semne_alarma','Semne de alarmă pentru antebraț — mergi la doctor',
 'amorțeală sau furnicături în degetele 1-3 (posibil tunel carpian), slăbiciune progresivă a prinderii, durere care nu cedează la repaus, umflare sau deformare după traumă, pierderea controlului mișcărilor fine, paloare sau răceală bruscă a mâinii.',
 9),
('muschi','muschii-antebratului','muschi:muschii-antebratului','antebrat',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la antebraț',
 'Durerea apare la tastare, prindere sau la mișcarea încheieturii? Este mai accentuată pe fața interioară (spredegetul mic) sau exterioară (spre police)? Ai amorțeală în degete? Durerea te trezește noaptea? Este legată de un sport sau activitate repetitivă?',
 5),

('muschi','muschii-mainii','muschi:muschii-mainii','mana',
 'anatomie','Mușchii mâinii — anatomie',
 'Mâna conține mușchi intrinseci: tenari (ridică, opun și aduc policele), hipotenari (mișcă degetul mic), interosoși (departează și apropie degetele) și lumbricali (flectează prima falangă, extind celelalte). Acești mușchi permit mișcări extrem de fine: precizie, prindere, ciupire, rotație.',
 8),
('muschi','muschii-mainii','muschi:muschii-mainii','mana',
 'simptome','Simptome frecvente la mușchii mâinii',
 'durere la strângerea pumnului sau prinderea obiectelor, slăbiciune la ciupire sau precizie, crampe în palmă (mai ales seara), sensibilitate la palpare pe palma sau între degete, rigiditate matinală, scăderea forței de prindere, durere la mișcarea degetelor.',
 7),
('muschi','muschii-mainii','muschi:muschii-mainii','mana',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii mâinii',
 'suprasolicitare prin activitate repetitivă (tastare, instrument muzical, sport), crampe, contuzie directă, artrită (mai ales la articulațiile mici ale degetelor), sindrom de tunel carpian (amorțeală police-arătător-mijlociu), trigger finger (deget blocat/clicant).',
 7),
('muschi','muschii-mainii','muschi:muschii-mainii','mana',
 'recomandari','Ce poți face pentru mușchii mâinii',
 'pauze și stretching al degetelor; exerciții de mobilitate (deschide-închide pumnul lent); aplicare de căldură pentru rigiditate matinală; evitarea prinderii forțate repetitive. Consultă un medic pentru amorțeală persistentă, slăbiciune, deformare sau durere care limitează activitățile zilnice.',
 6),
('muschi','muschii-mainii','muschi:muschii-mainii','mana',
 'semne_alarma','Semne de alarmă pentru mâna — mergi la doctor',
 'amorțeală persistentă în degete (posibil tunel carpian sau problemă cervicală), deformare articulară, imposibilitatea extinderii sau flexiei unui deget, degete palide sau reci brusc (problemă de circulație), pierderea controlului mișcărilor fine, durere severă după traumatism.',
 9),
('muschi','muschii-mainii','muschi:muschii-mainii','mana',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la mână',
 'Durerea este în palmă, în degete sau la articulații? Există amorțeală (și în ce degete)? Apare mai ales dimineața sau după efort? Un deget se blochează sau face clic? A fost lovitură sau accident? Ai și durere în antebraț sau umăr?',
 5),

('muschi','muschii-toracelui','muschi:muschii-toracelui','torace',
 'anatomie','Mușchii pieptului — anatomie',
 'Pectoral mare (mușchiul cel mai mare al pieptului) aduce brațul spre corp și îl rotește intern. Pectoral mic stabilizează omoplatul. Serratus anterior rotează omoplatul în sus. Intercostalii și diafragma sunt esențiali pentru respirație. Subclavicularul stabilizează clavicula.',
 8),
('muschi','muschii-toracelui','muschi:muschii-toracelui','torace',
 'simptome','Simptome frecvente la mușchii pieptului',
 'durere la mișcarea brațului spre interior sau la împins, tensiune musculară la palparea pectoralului, durere la respirație profundă (mușchi intercostali), crampe ale peretelui toracic, durere după efort intens la sală, senzație de strângere în piept legată de mișcarea brațului.',
 7),
('muschi','muschii-toracelui','muschi:muschii-toracelui','torace',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii pieptului',
 'suprasolicitare la împins (flotări, presă), contractură musculară, contuzie prin lovitură directă, tuse intensă prelungită (mușchi intercostali), ruptură parțială de pectoral după efort maximal. Durerea toracică poate fi și de cauze non-musculare (cardiacă, pleurală, costală) — este important de diferențiat.',
 7),
('muschi','muschii-toracelui','muschi:muschii-toracelui','torace',
 'recomandari','Ce poți face pentru mușchii pieptului',
 'evită mișcările de împins sau încrucișat brațele dacă sunt dureroase; odihnă; gheață în primele 24-48h după traumatism; stretching ușor al pectoralilor la ușă; consultă un medic dacă durerea este toracică anterioară intensă pentru a exclude cauze cardiace sau pleurale.',
 6),
('muschi','muschii-toracelui','muschi:muschii-toracelui','torace',
 'semne_alarma','Semne de alarmă pentru piept — mergi urgent la doctor',
 'URGENT: durere toracică intensă cu iradiere în brațul stâng, maxilar sau spate (posibil infarct); durere cu respirație dificilă, transpirație și senzație de rău (posibil problemă cardiacă sau pulmonară); durere severă la respirație cu febră (posibilă pleurezie sau pneumonie); deformare a coastelor după traumă.',
 9),
('muschi','muschii-toracelui','muschi:muschii-toracelui','torace',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la piept',
 'Durerea apare la mișcarea brațului sau la respirație? Sau este o durere care stă și în repaus? Iradiază spre brațul stâng sau spre spate? Ai dificultate de respirație, transpirații sau senzație de rău? A apărut după efort la sală sau după lovitură?',
 5),

('muschi','muschii-abdomenului','muschi:muschii-abdomenului','abdomen',
 'anatomie','Mușchii abdomenului — anatomie',
 'Peretele abdominal are patru straturi: dreptul abdominal (în față, "pătratele"), oblicul extern (strat superficial lateral), oblicul intern (strat profund lateral), transversul abdominal (cel mai profund, "corset natural"). Împreună susțin organele, stabilizează coloana, participă la respirație, tuse și mișcările trunchiului.',
 8),
('muschi','muschii-abdomenului','muschi:muschii-abdomenului','abdomen',
 'simptome','Simptome frecvente la mușchii abdomenului',
 'durere la răsucire sau aplecare a trunchiului, durere localizată la palpare pe peretele abdominal, sensibilitate după efort (abdominale, sport), crampe musculare, durere accentuată la tuse sau râs, rigiditate matinală a zonei abdominale, senzație de tensiune.',
 7),
('muschi','muschii-abdomenului','muschi:muschii-abdomenului','abdomen',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii abdomenului',
 'suprasolicitare la exerciții abdominale sau sport, contractură, contuzie directă, tuse prelungită intensă, întindere musculară la o mișcare bruscă. Important: durerea abdominală poate fi și de cauze interne (organe) — nu se poate presupune automat că este musculară.',
 7),
('muschi','muschii-abdomenului','muschi:muschii-abdomenului','abdomen',
 'recomandari','Ce poți face pentru mușchii abdomenului',
 'reducerea exercițiilor abdominale până la ameliorare; evitarea mișcărilor de răsucire dureroase; aplicare de căldură ușoară pe zona contractată. Consultă un medic dacă nu ești sigur că durerea este musculară, dacă este severă, dacă apare la repaus, dacă ai febră, greață sau tulburări intestinale.',
 6),
('muschi','muschii-abdomenului','muschi:muschii-abdomenului','abdomen',
 'semne_alarma','Semne de alarmă pentru abdomen — mergi urgent la doctor',
 'URGENT: durere abdominală severă și bruscă; durere cu febră, greață, vărsături sau tulburări intestinale (posibile cauze interne: apendicită, litiază, etc.); abdomen rigid ca o scândură; durere care nu poate fi legată de activitate musculară; sânge în scaun sau urină; durere care se agravează progresiv.',
 9),
('muschi','muschii-abdomenului','muschi:muschii-abdomenului','abdomen',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la abdomen',
 'Durerea apare la mișcare (răsucire, aplecare) sau și în repaus? A apărut după exerciții fizice sau după tuse? Există febră, greață sau vărsături? Poți lega durerea de o activitate fizică? Durerea este localizată sau difuză?',
 5),

('muschi','muschii-spatelui','muschi:muschii-spatelui','spate',
 'anatomie','Mușchii spatelui — anatomie',
 'Spatele are mai multe straturi: superficial (trapez — ridică și coboară umărul, marele dorsal — trage brațul în jos și înapoi, romboid — retrage omoplatul), și profund (erector spinae = iliocostal+longisimus+spinos — extind coloana, multifidus — stabilizează vertebrele, pătrat lombar — flexie laterală). Toți lucrează pentru postură și mișcarea trunchiului.',
 8),
('muschi','muschii-spatelui','muschi:muschii-spatelui','spate',
 'simptome','Simptome frecvente la mușchii spatelui',
 'durere lombară (zona inferioară a spatelui) sau dorsală (zona mijlocie), tensiune musculară palpabilă, spasm muscular paralizant, durere la aplecarea înainte sau înapoi, durere care se agravează după stat prelungit în șezut, oboseală musculară la muncă fizică, durere matinală care se ameliorează cu mișcarea.',
 7),
('muschi','muschii-spatelui','muschi:muschii-spatelui','spate',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii spatelui',
 'ridicare greșită a greutăților (cel mai frecvent), postură proastă prelungită, suprasolicitare la sport, dormit pe saltea nepotrivită, contractură după stat în curent, hernie de disc (durere care iradiază în picior), spondilolisteză. Cea mai frecventă cauză de durere lombară la adulți este musculo-ligamentară.',
 7),
('muschi','muschii-spatelui','muschi:muschii-spatelui','spate',
 'recomandari','Ce poți face pentru mușchii spatelui',
 'continuă mișcarea ușoară (repausul total la pat nu ajută, dimpotrivă); stretching al spatelui și al ischogambierilor; aplicare de căldură sau gheață (ce-ți aduce mai mult confort); corectarea posturii la birou; tehnica corectă de ridicare (cu genunchii, nu cu spatele). Consultă un medic dacă durerea persistă peste 6 săptămâni sau dacă iradiază în picior.',
 6),
('muschi','muschii-spatelui','muschi:muschii-spatelui','spate',
 'semne_alarma','Semne de alarmă pentru spate — mergi urgent la doctor',
 'durere în spate cu amorțeală sau slăbiciune în picior (posibilă compresie nervoasă); durere cu pierderea controlului vezicii sau intestinului (URGENȚĂ — sindrom de coadă de cal); durere nocturnă intensă care nu cedează la poziție (posibil tumoră); durere după traumatism sever; febră cu durere de spate (posibilă infecție spinală); durere la o persoană cu osteoporoză.',
 9),
('muschi','muschii-spatelui','muschi:muschii-spatelui','spate',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la spate',
 'Durerea este în zona lombară (jos), dorsală (mijloc) sau cervicală (gât)? Iradiază în fese, coapsă sau picior? A apărut după ridicare, mișcare bruscă sau fără cauză evidentă? Există amorțeală sau slăbiciune în picior? Te trezești noaptea din cauza durerii? Ai probleme la vezică sau intestin?',
 5),

('muschi','muschii-soldului','muschi:muschii-soldului','sold',
 'anatomie','Mușchii șoldului — anatomie',
 'Șoldul are mușchii fesieri (mare, mijlociu, mic) care extind, abduc și rotesc coapsa — gluteus maximus este cel mai puternic mușchi din corp. Profund: piriform, obturator, gemeni, pătrat femural — rotatori laterali ai coapsei. Iliopsoas (flexor al coapsei) merge din interior. Tensor fascia lata stabilizează lateral.',
 8),
('muschi','muschii-soldului','muschi:muschii-soldului','sold',
 'simptome','Simptome frecvente la mușchii șoldului',
 'durere în fesă sau lateral pe șold, durere la urcat scări sau la ridicarea din scaun, durere la mers prelungit, slăbiciune la urcat trepte, senzație de oboseală sau arsură în fesă după alergare, durere la palparea laterală a șoldului (bursită trohanterică), durere care coboară spre coapsă.',
 7),
('muschi','muschii-soldului','muschi:muschii-soldului','sold',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii șoldului',
 'suprasolicitare la alergare sau urcat (sindromul benzii ilio-tibiale), bursită trohanterică, contractură a piriformului (sindrom piriform — imitând sciatica), slăbiciunea fesierilor (durere lombară secundară), cădere pe fesă (contuzie), artrită de șold (durere în inghinală, nu în fesă).',
 7),
('muschi','muschii-soldului','muschi:muschii-soldului','sold',
 'recomandari','Ce poți face pentru mușchii șoldului',
 'stretching al piriformului și fesierilor (genunchiul la piept, rotație externă); reducerea alergării pe teren accidentat; gheață pe zona dureroasă; întărirea progresivă a fesierilor (exerciții cu rezistență mică). Consultă un medic dacă durerea este în inghinală (posibil articulație), dacă te împiedică să mergi sau dacă apare după cădere.',
 6),
('muschi','muschii-soldului','muschi:muschii-soldului','sold',
 'semne_alarma','Semne de alarmă pentru șold — mergi la doctor',
 'imposibilitate de a pune greutate pe picior după cădere (posibilă fractură de col femural — mai ales vârstnici), deformare sau rotație anormală a piciorului, durere severă în inghinală cu blocarea totală a mișcării, vânătaie extinsă, amorțeală sau slăbiciune progresivă în picior, durere nocturnă progresivă.',
 9),
('muschi','muschii-soldului','muschi:muschii-soldului','sold',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la șold',
 'Durerea este în fesă, pe lateralul șoldului sau în inghinală? Apare la alergare, la urcat scări sau și în repaus? A apărut după cădere sau fără cauză clară? Există amorțeală în picior? Poți merge normal? Ai mai mult de 60 ani?',
 5),

('muschi','muschii-coapsei','muschi:muschii-coapsei','coapsa',
 'anatomie','Mușchii coapsei — anatomie',
 'Coapsa are trei grupe: față — cvadricepsul (rectus femoris + 3 vaste) extinde genunchiul, sartoriusul flectează șoldul și genunchiul; spate — ischiogambierii (biceps femural, semitendinos, semimembranos) flectează genunchiul și extind șoldul; interior — adductorii (gracilis, pectineu, 3 adductori) apropie coapsa. Tensor fascia lata merge lateral.',
 8),
('muschi','muschii-coapsei','muschi:muschii-coapsei','coapsa',
 'simptome','Simptome frecvente la mușchii coapsei',
 'durere la alergare sau la urcat scări, crampe în coapsă, tensiune sau durere la întindere (stretch), slăbiciune la extensia genunchiului (cvadriceps), durere bruscă la sprint (ruptură musculară), sensibilitate la palpare, vânătaie localizată, durere la șezut prelungit (ischiogambieri).',
 7),
('muschi','muschii-coapsei','muschi:muschii-coapsei','coapsa',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii coapsei',
 'crampe (deshidratare, oboseală), febra musculară după antrenament (DOMS), întindere musculară (grad 1-2) la sprint sau schimbare bruscă de direcție, ruptură musculară (grad 3 — pocnet, pierdere completă de forță), contuzie directă (hematom), suprasolicitare la ciclism sau înot.',
 7),
('muschi','muschii-coapsei','muschi:muschii-coapsei','coapsa',
 'recomandari','Ce poți face pentru mușchii coapsei',
 'pentru crampe: stretching imediat și hidratare; pentru febra musculară: odihnă activă, mișcare ușoară; pentru întindere musculară: protocol RICE (Rest-Ice-Compression-Elevation) în primele 48h; revenire graduală la sport. Consultă un medic pentru durere severă cu pierdere de forță sau vânătaie mare.',
 6),
('muschi','muschii-coapsei','muschi:muschii-coapsei','coapsa',
 'semne_alarma','Semne de alarmă pentru coapsă — mergi la doctor',
 'pocnet urmat de durere intensă și pierdere completă de forță (posibilă ruptură completă); vânătaie extinsă rapidă; imposibilitate de mers; durere cu umflare mare și duritate la palpare (posibil sindrom de compartiment); durere la genunchi cu instabilitate (posibilă leziune ligamentară); durere nocturnă progresivă.',
 9),
('muschi','muschii-coapsei','muschi:muschii-coapsei','coapsa',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la coapsă',
 'Durerea este pe fața anterioară, posterioară sau interioară a coapsei? A apărut brusc în alergare sau treptat? Ai auzit sau simțit un pocnet? Există vânătaie sau umflare? Poți merge normal? Ai dificultate la urcat scări sau la extinderea genunchiului?',
 5),

('muschi','muschii-gambei','muschi:muschii-gambei','gamba',
 'anatomie','Mușchii gambei — anatomie',
 'Gamba are trei grupe: posterior superficial (gastrocnemian — molet, cel mai vizibil, flectează planta și genunchiul; soleus — sub gastrocnemian, flectează planta); posterior profund (flexor digitorum longus, tibial posterior, flexor hallucis — mișcă degetele și planta spre interior); anterior și lateral (tibial anterior — ridică vârful piciorului; fibulari — întorc planta spre exterior). Tendonul lui Ahile leagă gastrocnemianul și soleul de călcâi.',
 8),
('muschi','muschii-gambei','muschi:muschii-gambei','gamba',
 'simptome','Simptome frecvente la mușchii gambei',
 'crampe în molet (mai ales noaptea), durere la mers sau alergare pe fața posterioară a gambei, tensiune și durere la ridicarea pe vârfuri, durere pe fața anterioară la ridicarea piciorului (tibia anterioară), periostită tibială ("shin splints") la alergători, durere la palparea tendonului lui Ahile, umflare ușoară.',
 7),
('muschi','muschii-gambei','muschi:muschii-gambei','gamba',
 'cauze_posibile','Cauze frecvente ale durerii la mușchii gambei',
 'crampe (oboseală, deshidratare, deficit de magneziu), periostită tibială (alergare pe suprafețe dure), tendinopatie achiliană (suprasolicitare), întindere musculară a moletului, contractură, contuzie. Durerea în gambă cu umflare și roșeață poate indica tromboflebită (cheag) — necesită evaluare urgentă.',
 7),
('muschi','muschii-gambei','muschi:muschii-gambei','gamba',
 'recomandari','Ce poți face pentru mușchii gambei',
 'pentru crampe: stretching imediat al moletului (trage vârful piciorului spre tine), hidratare; pentru periostită tibială: reducerea alergării, antrenament pe suprafețe moi; pentru tendon Ahile: repaus și fizioterapie. Consultă un medic pentru durere severă, umflare cu roșeață (cheag?), imposibilitate de a calca.',
 6),
('muschi','muschii-gambei','muschi:muschii-gambei','gamba',
 'semne_alarma','Semne de alarmă pentru gambă — mergi urgent la doctor',
 'URGENT: gambă umflată, roșie și caldă cu durere la palpare (posibilă tromboză venoasă profundă — cheag de sânge); durere severă cu umflare rapidă după traumă; pocnet în zona tendonului Ahile cu pierderea forței de a ridica călcâiul (ruptură de Ahile); imposibilitate completă de mers; amorțeală sau răceală bruscă a piciorului.',
 9),
('muschi','muschii-gambei','muschi:muschii-gambei','gamba',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la gambă',
 'Durerea este în molet (spate), pe fața anterioară sau laterală? Apare la alergare sau și în repaus? Ai crampe noaptea? Gamba este umflată, roșie sau caldă? A apărut după sport sau fără cauză clară? Poți ridica vârful piciorului? Ai durere la tendonul lui Ahile (deasupra călcâiului)?',
 5),

('muschi','muschii-labei-piciorului','muschi:muschii-piciorului','picior',
 'anatomie','Mușchii labei piciorului — anatomie',
 'Laba piciorului conține mușchi intrinseci pe fața plantară (abductor hallucis — mișcă degetul mare spre exterior, flexor digitorum brevis, adductor hallucis, interosoși) și pe fața dorsală (extensor digitorum brevis). Susțin bolta longitudinală și transversală, permit mișcările degetelor și adaptează talpa la teren în mers.',
 8),
('muschi','muschii-labei-piciorului','muschi:muschii-piciorului','picior',
 'simptome','Simptome frecvente la mușchii labei piciorului',
 'crampe în talpă (mai ales seara), durere la primii pași dimineața (fasciită plantară), oboseală plantară după mers sau stat prelungit, durere localizată la palparea plantei, tensiune pe bolta plantară, durere la mișcarea degetelor, senzație de arsură sau presiune.',
 7),
('muschi','muschii-labei-piciorului','muschi:muschii-piciorului','picior',
 'cauze_posibile','Cauze frecvente ale durerii la laba piciorului',
 'fasciită plantară (cea mai frecventă: durere la primii pași dimineața), crampe (oboseală, deshidratare), suprasolicitare la alergare sau stat prelungit în picioare, încălțăminte neadecvată (talpă rigidă sau toc înalt), contuzie, fractură de stres (sportivi). Nevrom Morton dă durere și amorțeală între degetele 3-4.',
 7),
('muschi','muschii-labei-piciorului','muschi:muschii-piciorului','picior',
 'recomandari','Ce poți face pentru mușchii labei piciorului',
 'stretching al fasciei plantare dimineața (înainte de primul pas, trage degetele spre tine); masaj cu mingea de tenis sub talpă; încălțăminte cu susținere bună a bolții plantare; evitarea mersului desculț pe suprafețe dure. Consultă un medic pentru durere persistentă, amorțeală, deformare sau imposibilitate de sprijin.',
 6),
('muschi','muschii-labei-piciorului','muschi:muschii-piciorului','picior',
 'semne_alarma','Semne de alarmă pentru laba piciorului — mergi la doctor',
 'imposibilitate de a pune piciorul la sol după traumatism (posibilă fractură); deformare vizibilă; amorțeală sau furnicături persistente (posibilă compresie nervoasă); degete palide sau reci brusc (problemă vasculară); durere severă cu umflare rapidă; rană sau infecție la un diabetic (urgență).',
 9),
('muschi','muschii-labei-piciorului','muschi:muschii-piciorului','picior',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la laba piciorului',
 'Durerea apare la primii pași dimineața sau la calcat în general? Este pe talpă, pe degetele sau pe dosul piciorului? A apărut după alergare, lovitură sau fără cauză? Există umflare sau vânătaie? Ce tip de încălțăminte porți? Ai amorțeală în degete?',
 5),

('muschi','muschii-bazinului','muschi:muschii-bazinului','pelvis',
 'anatomie','Mușchii bazinului (planșeul pelvian) — anatomie',
 'Planșeul pelvian este format din levator ani (pubococcigian, iliococcigian), coccigian și mușchii sfincterieni. Susțin organele pelviene (vezică, uter/prostată, rect), controlează continența urinară și fecală și sunt implicați în funcția sexuală.',
 8),
('muschi','muschii-bazinului','muschi:muschii-bazinului','pelvis',
 'simptome','Simptome frecvente la mușchii bazinului',
 'durere sau presiune pelviana cronică, pierdere de urină la tuse/râs/efort (incontinență de efort), senzație de greutate pelviana, durere în zona coccisului, probleme la controlul vezicii sau intestinului, durere în timpul activității sexuale.',
 7),
('muschi','muschii-bazinului','muschi:muschii-bazinului','pelvis',
 'cauze_posibile','Cauze frecvente ale durerii la bazin',
 'slăbiciunea planșeului pelvian (după naștere, în sarcină, la vârstnici), hipertonie (mușchi prea contractați — cauză frecventă de durere pelviana cronică), traumatism coccisian (cădere), prostatită, endometrioză, sindrom de durere pelviana cronică.',
 7),
('muschi','muschii-bazinului','muschi:muschii-bazinului','pelvis',
 'recomandari','Ce poți face pentru mușchii bazinului',
 'exerciții Kegel (contractarea și relaxarea planșeului pelvian) pentru întărire sau relaxare progresivă; consultarea unui kinetoterapeut specializat în pelviperineologie. Durerea pelviana necesită evaluare medicală pentru excluderea cauzelor organice.',
 6),
('muschi','muschii-bazinului','muschi:muschii-bazinului','pelvis',
 'semne_alarma','Semne de alarmă pentru bazin — mergi urgent la doctor',
 'pierderea bruscă a controlului vezicii sau intestinului (posibilă urgență neurologică), durere pelviana severă bruscă cu febră (posibilă infecție), sângerare vaginală sau rectală inexplicabilă, durere foarte intensă după cădere pe coccis.',
 9),
('muschi','muschii-bazinului','muschi:muschii-bazinului','pelvis',
 'intrebari_clarificare','Întrebări pentru evaluarea durerii la bazin',
 'Durerea este continuă sau apare la anumite activități? Ai pierderi de urină la efort? Există dificultate la controlul vezicii sau intestinului? Durerea apare în activitatea sexuală? A fost naștere recentă sau traumatism în zonă?',
 5);


insert into public.ai_knowledge_entries
  (tissue, structure_slug, model_selection_id, body_region,
   category, title_ro, content_ro, priority)
values

('muschi','cvadriceps','cvadriceps','coapsa',
 'anatomie','Cvadricepsul — grupul muscular anterior al coapsei',
 'Cvadricepsul este format din 4 capete: rectus femoris, vastus lateralis, vastus medialis și vastus intermedius. Este cel mai puternic mușchi extensor al genunchiului și este esențial pentru mers, alergare, urcat scări și sărituri. Vastus medialis ("lacrima") stabilizează rotula.',
 8),
('muschi','cvadriceps','cvadriceps','coapsa',
 'simptome','Simptome la nivelul cvadricepsului',
 'durere pe fața anterioară a coapsei la alergare sau urcat scări, slăbiciune la extinderea genunchiului, durere la palpare pe coapsă, febra musculară după antrenament, durere bruscă la sprint sau schimbare de direcție (posibilă ruptură), tendinopatie patelară (durere la vârful rotulei).',
 7),
('muschi','cvadriceps','cvadriceps','coapsa',
 'cauze_posibile','Cauze durere cvadriceps',
 'febra musculară post-antrenament (DOMS), tendinopatie patelară (supra-solicitare la sportivi), contractură, ruptură parțială sau totală la sprint maximal, sindrom de durere patelofemurală (durere în jurul rotulei la urcat scări sau stat în șezut prelungit).',
 7),
('muschi','cvadriceps','cvadriceps','coapsa',
 'semne_alarma','Semne de alarmă cvadriceps',
 'pocnet cu pierdere completă de forță la extensia genunchiului (posibilă ruptură de tendon cvadricipital sau patelar); vânătaie extinsă rapidă; imposibilitate de mers sau de extins genunchiul; durere severă cu umflare mare după traumatism.',
 9),

('muschi','ischiogambieri','ischiogambieri','coapsa',
 'anatomie','Ischiogambierii — grupul muscular posterior al coapsei',
 'Ischiogambierii (biceps femural lung și scurt, semitendinos, semimembranos) flectează genunchiul, extind șoldul și rotesc gamba. Sunt cei mai frecvent lezați mușchi în sport — "ruptura la sprint". Bicepsul femural este cel mai lateral; semimembranosul cel mai profund.',
 8),
('muschi','ischiogambieri','ischiogambieri','coapsa',
 'simptome','Simptome la nivelul ischiogambierilor',
 'durere bruscă în coapsă posterioară la sprint sau mișcare explozivă, tensiune sau durere surdă în coapsă după alergare, durere la îndoirea genunchiului cu rezistență, sensibilitate la palpare posterior pe coapsă, vânătaie în zona posterioară, dificultate la alergare sau la extensia șoldului.',
 7),
('muschi','ischiogambieri','ischiogambieri','coapsa',
 'cauze_posibile','Cauze durere ischiogambieri',
 'întindere sau ruptură musculară la sprint, accelerare bruscă sau lovit de minge, dezechilibru de forță față-spate (cvadriceps mult mai puternic decât ischiogambierii), insuficienta încălzire, oboseală. Durerea cronică la locul de inserție (tuberozitate ischiatică) = tendinopatie proximală.',
 7),
('muschi','ischiogambieri','ischiogambieri','coapsa',
 'semne_alarma','Semne de alarmă ischiogambieri',
 'pocnet cu durere imediată intensă și imposibilitate de mers (posibilă ruptură completă); vânătaie extinsă rapid; durere la șezut care iradiază în picior (posibil tendon proximal rupt sau compresie nervos sciatic); forță redusă semnificativ la flexia genunchiului.',
 9),

('muschi','adductori','adductori','coapsa',
 'anatomie','Adductorii — grupul medial al coapsei',
 'Adductorii (adductor mare, lung, scurt, gracilis, pectineu) aduc coapsa spre linia mediană și contribuie la flexia/extensia șoldului. Gracilis este cel mai medial și lung, traversând și genunchiul. Sunt solicitați în schimbări de direcție, șuturi și jocuri cu minge.',
 8),
('muschi','adductori','adductori','coapsa',
 'simptome','Simptome la nivelul adductorilor',
 'durere pe fața internă a coapsei, durere la deschiderea picioarelor (abducție) sau la schimbarea de direcție, sensibilitate la palpare pe coapsă interioară, durere la șut sau la mișcări laterale, jenă sau durere la mers pe teren inegal.',
 7),
('muschi','adductori','adductori','coapsa',
 'cauze_posibile','Cauze durere adductori',
 'întindere sau ruptură musculară la mișcare laterală bruscă (fotbal, tenis, baschet), contuzie directă, suprasolicitare, "pubalgie" (sindrom de durere la nivelul pubisului și adductorilor la sportivi). Durerea în inghinală poate fi și hernie inghinală — necesită evaluare medicală.',
 7),
('muschi','adductori','adductori','coapsa',
 'semne_alarma','Semne de alarmă adductori',
 'durere în inghinală cu umflare (posibilă hernie sau leziune articulară de șold); pocnet cu pierdere de forță; imposibilitate de a aduce picioarele; durere severă persistentă care nu se ameliorează în câteva zile.',
 9),

('muschi','coafa-rotatorilor','coafa-rotatorilor','umar_centura_scapulara',
 'anatomie','Coafa rotatorilor — stabilizatorii profunzi ai umărului',
 'Coafa rotatorilor este formată din 4 mușchi profunzi: supraspinos (abducție inițială a brațului — cel mai frecvent afectat), infraspinos (rotație externă), subscapular (rotație internă), rotund mic (rotație externă și adducție). Împreună mențin capul humeral în cavitate în timp ce deltoidul ridică brațul.',
 8),
('muschi','coafa-rotatorilor','coafa-rotatorilor','umar_centura_scapulara',
 'simptome','Simptome la nivelul coafei rotatorilor',
 'durere la ridicarea brațului lateral (arc dureros între 60-120 grade), durere nocturnă pe umărul afectat, slăbiciune la rotația brațului, durere la pieptănat sau la îmbrăcat (mișcări ale brațului la spate), senzație de clicuri sau cracmente la mișcarea umărului, durere la palpare sub acromion.',
 7),
('muschi','coafa-rotatorilor','coafa-rotatorilor','umar_centura_scapulara',
 'cauze_posibile','Cauze durere coafă rotatorie',
 'impingement subacromian (tendonul prins între acromion și capul humeral) — cea mai frecventă cauză; tendinopatie degenerativă (uzură la vârstnici); ruptură parțială sau totală după efort brusc sau traumatism; calcifiere tendinoasă (calcificată = durere bruscă intensă); instabilitate cronică de umăr.',
 7),
('muschi','coafa-rotatorilor','coafa-rotatorilor','umar_centura_scapulara',
 'semne_alarma','Semne de alarmă coafă rotatorie',
 'pierderea completă a forței de ridicare a brațului (posibilă ruptură totală de coafă); imposibilitate de a ridica brațul lateral; durere severă acută cu impotență funcțională completă (posibil calcificate ruptă); deformare; durere progresivă care nu cedează la repaus sau antiinflamatoare.',
 9),

('muschi','muschii-fesieri','muschii-fesieri','sold',
 'anatomie','Mușchii fesieri — anatomie',
 'Gluteus maximus (fesierul mare) este cel mai puternic mușchi din corp: extinde și rotește lateral coapsa, esențial la urcat scări, alergat și ridicat din scaun. Gluteus medius și minimus (fesieri mijlociu și mic) abduc coapsa și stabilizează bazinul la fiecare pas. Slăbiciunea lor cauzează mers "în legănat" și durere lombară.',
 8),
('muschi','muschii-fesieri','muschii-fesieri','sold',
 'simptome','Simptome la nivelul mușchilor fesieri',
 'durere în fesă, slăbiciune la urcat scări sau la ridicarea dintr-un scaun jos, durere la alergare sau mers pe distanțe lungi, durere laterală pe șold (bursita trohanterică asociată), mers "în legănat" la slăbiciune bilaterală, oboseală precoce la sport, durere la palparea fesei.',
 7),
('muschi','muschii-fesieri','muschii-fesieri','sold',
 'cauze_posibile','Cauze durere mușchi fesieri',
 'insuficiența fesierilor (frecventă la cei care stau mult în șezut), suprasolicitare la alergare, bursită trohanterică (inflamație bursă pe lateralul șoldului), ruptură musculară la traumatism, sindrom piriform (piriformul irită nervul sciatic), contractură după sport de mare intensitate.',
 7),
('muschi','muschii-fesieri','muschii-fesieri','sold',
 'semne_alarma','Semne de alarmă mușchi fesieri',
 'imposibilitate de a te ridica din scaun sau de a merge după traumatism (posibilă fractură sau ruptură); durere în fesă cu iradiere pe tot piciorul — amorțeală până la picior (posibilă compresie nerv sciatic sau hernie de disc lombară); durere nocturnă progresivă inexplicabilă.',
 9),

('muschi','muschii-gambei','muschii-gambei','gamba',
 'anatomie','Mușchii gambei (moletul) — grupul posterior',
 'Gastrocnemianul și soleul formează moletul și sunt principalii flexori plantari — esențiali pentru mers, alergare și sărituri. Gastrocnemianul are două capete care se inseră deasupra genunchiului (deci flectează și genunchiul). Soleul este mai profund și mai rezistent la oboseală. Tendonul lui Ahile le unește de călcâi.',
 8),
('muschi','muschii-gambei','muschii-gambei','gamba',
 'simptome','Simptome la nivelul moletului',
 'crampe noaptea sau la efort, durere la ridicarea pe vârfuri, tensiune în molet după alergare, durere pe tendonul lui Ahile (deasupra călcâiului), slăbiciune la propulsie în mers sau alergare, senzație de "mușchi tras" în gambă.',
 7),
('muschi','muschii-gambei','muschii-gambei','gamba',
 'cauze_posibile','Cauze durere molet și tendon Ahile',
 'crampe (oboseală, deshidratare, magneziu scăzut), tendinopatie achiliană (suprasolicitare la alergători), ruptură de molet sau Ahile (pocnet + pierdere de forță la propulsie), periostită tibială, contuzie. ATENȚIE: gambă umflată + roșeață + căldură = posibil cheag de sânge (tromboză).',
 7),
('muschi','muschii-gambei','muschii-gambei','gamba',
 'semne_alarma','Semne de alarmă molet și Ahile',
 'gambă roșie, caldă și umflată cu durere (cheag de sânge — URGENȚĂ); pocnet la nivelul călcâiului cu imposibilitate de a ridica călcâiul de la sol (ruptură de Ahile); durere severă cu umflare rapidă după traumatism; imposibilitate de mers.',
 9),

('muschi','muschii-tibiali-peronieri','muschii-tibiali-peronieri','gamba',
 'anatomie','Mușchii tibiali și peronieri — controlul gleznei',
 'Tibialul anterior (fața anterioară a gambei) ridică vârful piciorului (dorsiflexie) și inversează planta — esențial pentru mers (împiedică bătaia vârfului de sol). Fibularii (lung și scurt, față laterală) eversează planta și stabilizează glezna lateral — previn entorsele.',
 8),
('muschi','muschii-tibiali-peronieri','muschii-tibiali-peronieri','gamba',
 'simptome','Simptome la tibiali și peronieri',
 'durere pe fața anterioară sau laterală a gambei la alergare, periostită tibială ("shin splints"), durere care apare după alergare pe asfalt, slăbiciune la ridicarea vârfului piciorului (picior căzut), instabilitate laterală a gleznei, durere la palpare pe maleola externă sau pe fața laterală a gambei.',
 7),
('muschi','muschii-tibiali-peronieri','muschii-tibiali-peronieri','gamba',
 'cauze_posibile','Cauze durere tibiali și peronieri',
 'periostită tibială (creștere bruscă de volum de antrenament), ruptură de tendon peronier (entorsă repetată), entorsă de gleznă cu lezare de fibulari, sindrom de compartiment anterior (rar, durere la efort cu gambă foarte dură), fractura de stres a tibiei la alergători.',
 7),
('muschi','muschii-tibiali-peronieri','muschii-tibiali-peronieri','gamba',
 'semne_alarma','Semne de alarmă tibiali și peronieri',
 'gambă anterioară sau laterală extrem de dură și dureroasă la efort cu senzație de presiune internă (posibil sindrom de compartiment acut — URGENȚĂ CHIRURGICALĂ); picior căzut (drop foot) — imposibilitate de a ridica vârful piciorului (leziune nervos sau musculară gravă); fractură de stres (durere la palpare pe tibie, agravată la alergare).',
 9),

('muschi','muschii-spatelui-superficiali','muschii-spatelui-superficiali','spate',
 'anatomie','Mușchii superficiali ai spatelui — trapez și marele dorsal',
 'Trapezul (superior, mijlociu, inferior) ridică, retrage și coboară omoplatul și susține capul. Marele dorsal este cel mai mare mușchi al spatelui: aduce și coboară brațul, rotește intern humersul. Romboidul retrage omoplatul. Levator scapulae ridică omoplatul și înclină gâtul lateral. Toți sunt activi în tracțiune, canotaj, înot.',
 8),
('muschi','muschii-spatelui-superficiali','muschii-spatelui-superficiali','spate',
 'simptome','Simptome mușchi superficiali spate',
 'durere interscapulară (între omoplați), tensiune și sensibilitate la palpare pe trapez (mai ales superior), durere la rotația sau aplecarea trunchiului, durere la tras sau ridicat brațul, senzație de omoplat "blocat" sau clicuri la mișcarea umărului.',
 7),
('muschi','muschii-spatelui-superficiali','muschii-spatelui-superficiali','spate',
 'cauze_posibile','Cauze durere mușchi superficiali spate',
 'postură cifotica (rotunjirea umerilor) cu suprasolicitarea romboidilor și trapezului mijlociu, stat prelungit la birou, sport de tracțiune (canotaj, escaladă), contractură de trapez superior (stres, tensiune), contuzie directă, dezechilibru muscular față-spate.',
 7),
('muschi','muschii-spatelui-superficiali','muschii-spatelui-superficiali','spate',
 'semne_alarma','Semne de alarmă mușchi spate superficiali',
 'durere interscapulară bruscă și foarte intensă cu iradiere spre piept sau abdomen (posibilă disecție de aortă sau problemă cardiacă — URGENȚĂ); durere progresivă fără cauză musculară identificabilă; amorțeală sau slăbiciune în brațe.',
 9),

('muschi','muschii-spatelui-profunzi','muschii-spatelui-profunzi','spate',
 'anatomie','Mușchii profunzi ai spatelui — erector spinae și multifidus',
 'Erector spinae (iliocostal, longisimus, spinos) extind și stabilizează coloana în poziție verticală. Multifidus are fascicule scurte între vertebre adiacente — stabilizator fin al coloanei, atrofiat frecvent după durere lombară. Pătrat lombar: flexie laterală și stabilizare a lombelor. Toți participă la postura statică și la ridicare.',
 8),
('muschi','muschii-spatelui-profunzi','muschii-spatelui-profunzi','spate',
 'simptome','Simptome mușchi profunzi spate',
 'durere lombară la ridicare sau aplecare, spasm muscular paralizant, durere la trezire (diminuată după încălzire), dificultate la statul ridicat prelungit, durere acutizată la tuse sau strănut, sensibilitate la palpare paravertebrală (lângă coloană).',
 7),
('muschi','muschii-spatelui-profunzi','muschii-spatelui-profunzi','spate',
 'cauze_posibile','Cauze durere mușchi profunzi spate',
 'ridicare greșită, postură prelungită în flexie, hernie de disc (cu compresie radiculară), spondilolisteză, atrofia multifidusului după episod de lombalgii, oboseală musculară la muncă fizică intensă, contractură.',
 7),
('muschi','muschii-spatelui-profunzi','muschii-spatelui-profunzi','spate',
 'semne_alarma','Semne de alarmă mușchi profunzi spate',
 'durere lombară cu iradiere în picior și amorțeală/slăbiciune (compresie nervoasă — hernie de disc); pierderea controlului vezicii sau intestinului (URGENȚĂ — sindrom cauda equina); durere nocturnă progresivă sau durere la persoana cu osteoporoză sau cancer în antecedente; febră cu durere de spate.',
 9),

('muschi','muschii-abdominali','muschii-abdominali','abdomen',
 'anatomie','Mușchii abdominali — detalii subgrupă',
 'Dreptul abdominal (rectus abdominis) flexează trunchiul pe bazin și este vizibil ca "pătratele" la tonificat. Oblicul extern (strat superficial) rotește trunchiul spre partea opusă. Oblicul intern rotește spre aceeași parte. Transversul (cel mai profund) este "corsetul natural" — comprima abdomenul și stabilizează coloana fără mișcare vertebrală.',
 8),
('muschi','muschii-abdominali','muschii-abdominali','abdomen',
 'simptome','Simptome la mușchii abdominali',
 'durere la abdominale sau la ridicarea din pat, sensibilitate la palpare pe dreapta sau stânga, crampe după efort intens, hernie ombilicală sau inghinală (bombament vizibil), diastasis recti (separarea dreptului abdominal — frecvent postpartum).',
 7),
('muschi','muschii-abdominali','muschii-abdominali','abdomen',
 'semne_alarma','Semne de alarmă abdominali',
 'durere abdominală cu febră, greață, vărsături sau tulburări de tranzit (posibilă cauză internă — apendicită, ocluzie); bombament dureros la efort (hernie strangulată — URGENȚĂ); durere severă bruscă "în pumnal" (posibilă urgență abdominală).',
 9),

('muschi','muschii-pieptului','muschii-pieptului','torace',
 'anatomie','Mușchii pieptului — pectoral mare și mic',
 'Pectoral mare: adducție, flexie și rotație internă a brațului — esențial la împins (flotări, presă). Pectoral mic: coboară și protractă omoplatul; la sportivii cu piept antrenat, poate comprima vasele și nervii spre braț (sindrom de ieșire toracică). Serratus anterior rotează omoplatul în sus — esențial la ridicarea brațului.',
 8),
('muschi','muschii-pieptului','muschii-pieptului','torace',
 'simptome','Simptome la mușchii pieptului',
 'durere la împins sau la ducerea brațului spre interior, tensiune la palparea pectoralului, durere la încrucișarea brațelor, amorțeală în braț (sindrom de ieșire toracică), durere bruscă cu deformare la efort maximal (ruptură pectoral), senzație de strângere în piept la mișcare.',
 7),
('muschi','muschii-pieptului','muschii-pieptului','torace',
 'semne_alarma','Semne de alarmă mușchi piept',
 'URGENT: durere în piept cu iradiere în braț stâng sau maxilar (posibil infarct — apelează 112); pocnet la nivelul pectoralului cu deformare și pierdere de forță (ruptură completă pectoral); durere cu dificultate de respirație și febră.',
 9),

('muschi','muschii-gatului','muschii-gatului','cap_gat',
 'anatomie','Mușchii gâtului — sternocleidomastoidian și scaleni',
 'Sternocleidomastoidianul (SCM) rotește capul spre partea opusă și îl înclină spre aceeași parte — mușchiul cel mai vizibil al gâtului. Scalenii (anterior, mijlociu, posterior) flectează lateral gâtul și ridică primele coaste la inspirație forțată. Platysma — mușchiul superficial al gâtului. Toți sunt implicați în postura capului.',
 8),
('muschi','muschii-gatului','muschii-gatului','cap_gat',
 'simptome','Simptome la mușchii gâtului',
 'durere la întoarcerea capului, torticolis (cap blocat într-o poziție), tensiune palpabilă pe SCM sau scaleni, durere care iradiază spre ureche sau spre umăr, cefalee occipitală, dificultate la rotația completă a gâtului.',
 7),
('muschi','muschii-gatului','muschii-gatului','cap_gat',
 'semne_alarma','Semne de alarmă gât',
 'durere de gât după traumatism cu amorțeală sau slăbiciune în membre (posibilă leziune cervicală — nu mișca pacientul, apelează 112); torticolis la nou-născut sau copil mic (consultare pediatrică); durere severă cu febră și rigiditate la flectarea gâtului (posibilă meningită — URGENȚĂ).',
 9),

('muschi','muschii-masticatori','muschii-masticatori','cap_gat',
 'anatomie','Mușchii masticatori — mestecat și articulația temporomandibulară',
 'Maseterul (palpabil pe obraz la strângerea dinților) și temporalul (pe tâmplă) închid gura și strâng mandibula. Pterigoidul medial și lateral deplasează mandibula lateral și ajută la deschiderea gurii. Toți acționează asupra articulației temporo-mandibulare (ATM). Bruxismul (scrâșnit din dinți) suprasolicită acești mușchi.',
 8),
('muschi','muschii-masticatori','muschii-masticatori','cap_gat',
 'simptome','Simptome la mușchii masticatori (ATM)',
 'durere la mestecat sau la deschiderea largă a gurii, cracmente sau clicuri în articulația mandibulei, oboseală la mestecat, durere de cap temporală (temporalul contractat), durere de ureche fără infecție, dificultate la deschiderea completă a gurii, durere nocturnă la cei cu bruxism.',
 7),
('muschi','muschii-masticatori','muschii-masticatori','cap_gat',
 'cauze_posibile','Cauze durere mușchi masticatori',
 'bruxism (scrâșnit din dinți nocturn), stres cu contractura maseterului, disfuncție ATM, malocluzie dentară (dinți care nu se potrivesc corect), postură proastă a capului, artrite ale ATM.',
 7),
('muschi','muschii-masticatori','muschii-masticatori','cap_gat',
 'semne_alarma','Semne de alarmă mușchi masticatori',
 'blocaj de mandibulă (nu poți nici închide nici deschide gura), durere severă unilaterală cu umflare (posibilă abces dentar sau infecție); trismus (imposibilitate deschidere gură) cu febră; traumatism mandibular cu suspiciune de fractură.',
 9),

('muschi','muschii-soldului-profunzi','muschii-soldului-profunzi','sold',
 'anatomie','Mușchii profunzi ai șoldului — rotatorii externi',
 'Grupul rotatorilor externi profunzi: piriform, obturator intern și extern, gemenii (superior și inferior), pătrat femural. Toți rotează lateral coapsa și stabilizează articulația șoldului. Piriformul trece peste nervul sciatic — contractura sa poate comprima sciaticul (sindrom piriform).',
 8),
('muschi','muschii-soldului-profunzi','muschii-soldului-profunzi','sold',
 'simptome','Simptome la mușchii profunzi ai șoldului',
 'durere profundă în fesă, durere la rotația externă a piciorului, disconfort la șezut prelungit (mai ales pe piriform), durere care iradiază pe fața posterioară a coapsei (imitând sciatica), durere la mers pe teren accidentat, sensibilitate la palpare profundă a fesei.',
 7),
('muschi','muschii-soldului-profunzi','muschii-soldului-profunzi','sold',
 'cauze_posibile','Cauze durere rotatori profunzi șold',
 'sindrom piriform (contractura piriformului comprimă nervul sciatic — mai frecvent la alergători și cicliști), suprasolicitare la mișcări de rotație externă (dans, arte marțiale), contuzie directă pe fesă, hematom profund.',
 7),
('muschi','muschii-soldului-profunzi','muschii-soldului-profunzi','sold',
 'semne_alarma','Semne de alarmă rotatori profunzi',
 'durere în fesă cu iradiere pe tot membrul inferior (amorțeală, furnicături până la picior) care nu se ameliorează cu repaus (posibilă compresie nervoasă semnificativă sau hernie de disc lombară); durere nocturnă progresivă fără cauză identificabilă.',
 9),

('muschi','muschii-bratului-anteriori','muschii-bratului-anteriori','brat',
 'anatomie','Mușchii anteriori ai brațului — biceps și brahial',
 'Bicepsul brahial (două capete: lung — trece prin șanțul bicipital; scurt — de pe coracoid) flectează cotul, supinează antebrațul și contribuie la flexia umărului. Brahialul este sub biceps și este cel mai puternic flexor pur al cotului. Coracobrahialul aduce brațul spre corp.',
 8),
('muschi','muschii-bratului-anteriori','muschii-bratului-anteriori','brat',
 'simptome','Simptome la mușchii anteriori ai brațului',
 'durere la îndoirea cotului cu rezistență (transport greutăți), durere la palpare pe biceps, crampe după efort intens cu greutăți, durere în umăr pe capul lung al bicepsului (tendinopatie bicipitală), senzație de "mușchi tras" după ridicare bruscă.',
 7),
('muschi','muschii-bratului-anteriori','muschii-bratului-anteriori','brat',
 'semne_alarma','Semne de alarmă biceps',
 'pocnet la nivelul cotului sau umărului cu deformare vizibilă a brațului și pierdere de forță (ruptură de tendon bicipital proximal sau distal); vânătaie extinsă rapidă; slăbiciune marcată la flexie sau supinație.',
 9),

('muschi','muschii-bratului-posteriori','muschii-bratului-posteriori','brat',
 'anatomie','Mușchii posteriori ai brațului — triceps și anconeu',
 'Tricepsul brahial (trei capete: lung — de pe omoplat; lateral și medial — de pe humerus) extinde cotul — esențial la împins, aruncat și la suport cu brațele. Anceul este un mic mușchi triunghiular lângă cot care ajută extensia. Tricepsul reprezintă aproximativ 2/3 din masa musculară a brațului.',
 8),
('muschi','muschii-bratului-posteriori','muschii-bratului-posteriori','brat',
 'simptome','Simptome la triceps',
 'durere la extinderea cotului cu rezistență (împins la sală), tensiune la palpare posterior pe braț, febra musculară după antrenament intens de triceps, durere la tendonul tricepsal (deasupra olecranului), durere după aruncat sau lovit mingea.',
 7),
('muschi','muschii-bratului-posteriori','muschii-bratului-posteriori','brat',
 'semne_alarma','Semne de alarmă triceps',
 'pocnet la nivelul cotului posterior cu pierdere de forță la extensie și deformare (posibilă ruptură de tendon tricipital — rar, dar există); cotul umflat și dureros după cădere pe mână întinsă (posibilă fractură de olecran — nu ruptură musculară).',
 9);


insert into public.ai_knowledge_entries
  (tissue, structure_slug, model_selection_id, body_region,
   category, title_ro, content_ro, priority)
values

('os','schelet-cap','os:craniu','cap_craniu',
 'anatomie','Oasele capului — craniu',
 'Craniul protejează encefalul (neurocraniu: frontal, parietal, temporal, occipital, sfenoid, etmoid) și formează structura feței (viscerocraniu: maxilar, mandibulă, zigomatic, nazal). Oasele feței susțin dinții, formează orbitele și cavitățile nazale. Singura articulație mobilă este mandibula (articulația temporomandibulară).',
 8),
('os','schelet-cap','os:craniu','cap_craniu',
 'semne_alarma','Semne de alarmă pentru oasele capului',
 'traumatism cranian cu pierdere de cunoștință sau confuzie (URGENȚĂ — 112); durere de cap bruscă și foarte intensă (posibilă hemoragie subarahnoidiană); deformare sau bombament cranian; scurgere de lichid clar din ureche sau nas după traumatism (lichid cefalorahidian — URGENȚĂ).',
 9),

('os','schelet-coloana','os:coloana','coloana',
 'anatomie','Coloana vertebrală',
 'Coloana are 33-34 vertebre: 7 cervicale (C1-C7), 12 toracice (T1-T12), 5 lombare (L1-L5), 5 sacrale fuzionate (sacrum), 3-5 coccigiene fuzionate (coccis). Fiecare vertebră are un corp (rezistență), un arc vertebral (protecție măduvă) și apofize (inserții musculare). Discurile intervertebrale amortizează șocurile.',
 8),
('os','schelet-coloana','os:coloana','coloana',
 'semne_alarma','Semne de alarmă pentru coloana vertebrală',
 'durere de coloană cu amorțeală sau slăbiciune în membre (compresie nervoasă); pierderea controlului vezicii/intestinului (URGENȚĂ — sindrom cauda equina); traumatism cu suspiciune de fractură vertebrală (nu mobiliza pacientul); durere nocturnă progresivă; deformare bruscă a coloanei.',
 9),

('os','schelet-torace','os:torace','torace',
 'anatomie','Oasele toracelui — coaste și stern',
 'Cutia toracică: 12 perechi de coaste (7 "adevărate" articulate cu sternul, 3 "false" unite prin cartilaj costal, 2 "flotante" fără articulație anterioară) + stern (manubriu, corp, xifoid). Protejează inima, plămânii și marile vase. Sternul este punct de referință pentru resuscitare cardiopulmonară.',
 8),
('os','schelet-torace','os:torace','torace',
 'semne_alarma','Semne de alarmă pentru oasele toracelui',
 'durere toracică cu dificultate de respirație și scădere de tensiune după traumatism (posibil pneumotorax sau hemotorax — URGENȚĂ); fractură costală cu respira paradoxal (volet costal — URGENȚĂ); durere sternală cu iradiere în braț stâng (posibil cardiac — URGENȚĂ 112).',
 9),

('os','schelet-membrul-superior','os:antebrat','antebrat',
 'anatomie','Oasele membrului superior',
 'Membrul superior: humerus (brațul), radius și ulnă (antebrațul), 8 carpiene (încheietura), 5 metacarpiene (palma), 14 falange (degetele — 2 la police, 3 la fiecare deget). Articulațiile principale: umăr (cea mai mobilă), cot (balamă), radioulnară (rotație antebraț), pumn (încheietura), MCF și IFP (degetele).',
 8),
('os','schelet-membrul-superior','os:antebrat','antebrat',
 'semne_alarma','Semne de alarmă pentru oasele membrului superior',
 'deformare vizibilă după traumatism (posibilă fractură sau luxație); imposibilitate de mișcare a articulației după cădere; vânătaie extinsă rapidă; amorțeală sau slăbiciune distal de traumatism; mână rece sau palidă brusc după traumatism (posibil compromis vascular).',
 9),

('os','schelet-membrul-inferior','os:gamba','gamba',
 'anatomie','Oasele membrului inferior',
 'Membrul inferior: femur (cel mai lung os din corp), rotulă (os sesamoid al genunchiului), tibia și fibula (gamba), 7 tarsiene (glezna și partea posterioară a piciorului — calcaneu, talus etc.), 5 metatarsiene, 14 falange. Articulații principale: șold (bilă-cavitate), genunchi (cea mai mare articulație), gleznă, articulații ale piciorului.',
 8),
('os','schelet-membrul-inferior','os:gamba','gamba',
 'semne_alarma','Semne de alarmă pentru oasele membrului inferior',
 'imposibilitate de a pune greutate după traumatism (posibilă fractură — mai ales col femural la vârstnici); deformare vizibilă; vânătaie și umflare rapidă; amorțeală sau slăbiciune distal; gambă umflată și roșie fără traumatism (posibil cheag de sânge — URGENȚĂ).',
 9);
